# Generated by Django 3.2.11 on 2022-01-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5, verbose_name='Precio'),
        ),
    ]
